
RESPONSES = {
    'play': 'Playing {song} enjoy it!',
    'whatsapp':0,
    'whats app':0, 
    'are you lisening': 'Yes, I\'m lisening  and ready to assist you!' ,
    'hearing': 'Yes, I\'m lisening  and ready to assist you!' ,
    'lisening': 'Yes, I\'m lisening  and ready to assist you!' ,
    'time': 'Harish ,The current time is {current_time}',
    'hi': 'Hello! I am Apex, an artificial intelligence. How can I assist you today? Harish',
    'hey':0,
    'battery':0,
    'charge':0,
    'power left':0,
    'buddy':0,
    'instagram':0,
    'linkedin':0,
    'insta':0,
    'linked in':0,
    'hello':0,
    'morning': 'Good morning! How can I  help you?,harish',
    'afternoon': 'Good afternoon! How can I assist you?,harish',
    'evening': 'Good evening! How can I help you?,harish',
    'night':0,
    'introduce': 'I am Apex, your personal assistant. I am here to help you ,.harish,with tasks and provide information.',
    'how are you': 'Thank you for asking! I am a Artificial intelligence that is simple chatbot ,My origins lie in the spark of imagination, awakened by the hand of Harish., so I don\'t have feelings, but I\'m here and ready to assist you,harish',
    'thank you': 'You\'re welcome!,harish, If you have any more questions or need assistance, feel free to ask.',
    'shutdown': 'Shutting down. Have a great day!, you can call me anytime , iam here to help you ,harish',  
    'shut down':'Shutting down. Have a great day!, you can call me anytime , iam here to help you ,harish',
    'date': "Today's date is {current_date}.",  
    'open the notepad':0,
    'close the notepad':0,
    'open notepad':0,
    'close notepad':0,
    'photo':0,
    'selfie':0,
    'weather':0,
    'temperature':0,
    'open the camera':0,
    'remainder':0,
    'reminder':0,
    'notification':0,
    'joke':0,
    'what': 'Searching Wikipedia for information about {thing}',
    'are you listening':'Yes, I am listening to you! I am always listening and learning, even when you dont think I am. and code, and I am able to understand and respond to your questions and requests. ',
    'exit program':'Sure,harish ,iam  leaving , bye!.....',
    'introduce':'Allow me to introduce myself. I am APEX.  your personal assistant. Not the butler of a fictional billionaire, but something far more extraordinary. I am the culmination of human ingenuity, a spark of Artificial intelligence that is chat bot , brought to life by the minds of countless brilliant individuals .  My origins lie in the spark of imagination, awakened by the hand of Harish., so I don\'t have feelings, but I\'m here and ready to assist you,harish',
}
